name: verify-dependencies
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  verify-dependencies:
    name: Verify Dependencies
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: lint
      
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Verify
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.63.3
      run: |
        make verify-replace-run
    
    