name: verify-dependencies
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  verify-dependencies:
    name: Verify Dependencies
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.0

    - name: Verify
      run: |
        make verify-replace-run
        echo 'test'
        echo $ERRORREPOLIST
        echo $ERRORREPOLIST >> $GITHUB_ENV
    
    - name: Comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ env.ERRORREPOLIST}}
          })